"""empty message

Revision ID: 01b5afd9777e
Revises: 10dce14dc38d
Create Date: 2022-07-25 13:47:18.978258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b5afd9777e'
down_revision = '10dce14dc38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_date', sa.String(length=32), nullable=True),
    sa.Column('interviewer', sa.String(length=32), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###
