"""empty message

Revision ID: 03e2e8158f49
Revises: 0e1dedc0ba85
Create Date: 2022-07-29 10:06:13.797869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e2e8158f49'
down_revision = '0e1dedc0ba85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalities', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'modalities', ['student_id'])
    op.create_foreign_key(None, 'modalities', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modalities', type_='foreignkey')
    op.drop_constraint(None, 'modalities', type_='unique')
    op.drop_column('modalities', 'student_id')
    # ### end Alembic commands ###
