"""empty message

Revision ID: 046fb8517d8e
Revises: 03e2e8158f49
Create Date: 2022-07-29 10:49:42.262615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046fb8517d8e'
down_revision = '03e2e8158f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modalities_student_id_key', 'modalities', type_='unique')
    op.drop_constraint('modalities_student_id_fkey', 'modalities', type_='foreignkey')
    op.drop_column('modalities', 'student_id')
    op.add_column('students', sa.Column('modality', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'modality')
    op.add_column('modalities', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('modalities_student_id_fkey', 'modalities', 'students', ['student_id'], ['id'])
    op.create_unique_constraint('modalities_student_id_key', 'modalities', ['student_id'])
    # ### end Alembic commands ###
