"""empty message

Revision ID: 0e1dedc0ba85
Revises: 36008f1d0faa
Create Date: 2022-07-29 09:59:28.279127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1dedc0ba85'
down_revision = '36008f1d0faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_parents', sa.String(length=32), nullable=True),
    sa.Column('street', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('zipcode', sa.String(length=32), nullable=True),
    sa.Column('school', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('modalities')
    # ### end Alembic commands ###
