"""empty message

Revision ID: 10dce14dc38d
Revises: 2f97525a3424
Create Date: 2022-07-22 19:00:01.813817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dce14dc38d'
down_revision = '2f97525a3424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutoring', sa.Column('start_date', sa.String(length=32), nullable=True))
    op.add_column('tutoring', sa.Column('end_date', sa.String(length=32), nullable=True))
    op.drop_column('tutoring', 'ending_date')
    op.drop_column('tutoring', 'starting_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutoring', sa.Column('starting_date', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('tutoring', sa.Column('ending_date', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('tutoring', 'end_date')
    op.drop_column('tutoring', 'start_date')
    # ### end Alembic commands ###
