"""empty message

Revision ID: 1446940659c6
Revises: fff6fbd467fb
Create Date: 2022-08-04 20:59:46.491046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1446940659c6'
down_revision = 'fff6fbd467fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('subject', sa.String(length=32), nullable=True))
    op.drop_column('course', 'student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('student', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('course', 'subject')
    # ### end Alembic commands ###
