"""empty message

Revision ID: 1ea9f089c20c
Revises: d6944ee052ee
Create Date: 2022-10-01 14:49:39.289723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea9f089c20c'
down_revision = 'd6944ee052ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'upload', ['user_id'])
    op.create_foreign_key(None, 'upload', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload', type_='foreignkey')
    op.drop_constraint(None, 'upload', type_='unique')
    op.drop_column('upload', 'user_id')
    # ### end Alembic commands ###
