"""empty message

Revision ID: 20ab9f243228
Revises: e362cf7826b2
Create Date: 2022-08-02 08:37:43.770727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ab9f243228'
down_revision = 'e362cf7826b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('availabilities_user_avail_owner_fkey', 'availabilities', type_='foreignkey')
    op.create_foreign_key(None, 'availabilities', 'tutoring', ['user_avail_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availabilities', type_='foreignkey')
    op.create_foreign_key('availabilities_user_avail_owner_fkey', 'availabilities', 'user', ['user_avail_owner'], ['id'])
    # ### end Alembic commands ###
