"""empty message

Revision ID: 2484fdae8c18
Revises: df4b4c363927
Create Date: 2022-08-04 19:11:29.827462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2484fdae8c18'
down_revision = 'df4b4c363927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_table')
    op.add_column('course', sa.Column('selected_day', sa.String(length=32), nullable=True))
    op.alter_column('course', 'tutor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'student',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('course', 'course_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_day', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.alter_column('course', 'student',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course', 'tutor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('course', 'selected_day')
    op.create_table('course_table',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_table_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='course_table_student_id_fkey'),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], name='course_table_tutor_id_fkey')
    )
    # ### end Alembic commands ###
