"""empty message

Revision ID: 248f0815022b
Revises: ba3506592568
Create Date: 2022-07-31 19:31:23.173482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248f0815022b'
down_revision = 'ba3506592568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('user_subjects_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'tutoring', ['user_subjects_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'user_subjects_owner')
    # ### end Alembic commands ###
