"""empty message

Revision ID: 29ff848f57ec
Revises: 2ed50947f5f7
Create Date: 2022-07-31 08:24:39.107379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ff848f57ec'
down_revision = '2ed50947f5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('user_avail_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'availabilities', 'user', ['user_avail_owner'], ['id'])
    op.drop_column('students', 'avail_from')
    op.drop_column('students', 'avail_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('avail_to', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('avail_from', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'availabilities', type_='foreignkey')
    op.drop_column('availabilities', 'user_avail_owner')
    # ### end Alembic commands ###
