"""empty message

Revision ID: 2a2838cab69c
Revises: 7788eab991b5
Create Date: 2022-07-30 12:27:06.791372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2838cab69c'
down_revision = '7788eab991b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_possible', sa.Column('subject_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject_possible', 'students', ['subject_owner'], ['id'])
    op.drop_constraint('subjects_subject_owner_fkey', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'subject_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('subject_owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subjects_subject_owner_fkey', 'subjects', 'students', ['subject_owner'], ['id'])
    op.drop_constraint(None, 'subject_possible', type_='foreignkey')
    op.drop_column('subject_possible', 'subject_owner')
    # ### end Alembic commands ###
