"""empty message

Revision ID: 31a3f2d84aa1
Revises: 4f989fb04a84
Create Date: 2022-08-02 09:37:49.347022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a3f2d84aa1'
down_revision = '4f989fb04a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_to_study',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=32), nullable=True),
    sa.Column('subject_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_owner'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('subject_possible_subject_owner_fkey', 'subject_possible', type_='foreignkey')
    op.drop_column('subject_possible', 'subject_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_possible', sa.Column('subject_owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subject_possible_subject_owner_fkey', 'subject_possible', 'students', ['subject_owner'], ['id'])
    op.drop_table('subject_to_study')
    # ### end Alembic commands ###
