"""empty message

Revision ID: 3dbc01e38474
Revises: 31a3f2d84aa1
Create Date: 2022-08-04 16:17:36.984677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbc01e38474'
down_revision = '31a3f2d84aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('tutor', sa.Integer(), nullable=False),
    sa.Column('student', sa.Integer(), nullable=False),
    sa.Column('course_day', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['student'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tutor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'tutor', 'student'),
    sa.UniqueConstraint('id')
    )
    op.create_table('course_table',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_table')
    op.drop_table('course')
    # ### end Alembic commands ###
