"""empty message

Revision ID: 4ac615620bc4
Revises: 4b4a5c8519fe
Create Date: 2022-07-21 13:12:33.682014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac615620bc4'
down_revision = '4b4a5c8519fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_filename', sa.String(length=50), nullable=True),
    sa.Column('cv_data', sa.LargeBinary(), nullable=True),
    sa.Column('b3_filename', sa.String(length=50), nullable=True),
    sa.Column('b3_data', sa.LargeBinary(), nullable=True),
    sa.Column('id_filename', sa.String(length=50), nullable=True),
    sa.Column('id_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'upload', ['upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'upload_id')
    op.drop_table('upload')
    # ### end Alembic commands ###
