"""empty message

Revision ID: 4f989fb04a84
Revises: 20ab9f243228
Create Date: 2022-08-02 08:51:08.350246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f989fb04a84'
down_revision = '20ab9f243228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalities_possible',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modalities_possible')
    # ### end Alembic commands ###
