"""empty message

Revision ID: 5b85ed88dbc2
Revises: fcf5be0f2807
Create Date: 2022-07-22 09:31:49.029348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b85ed88dbc2'
down_revision = 'fcf5be0f2807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('more_about_me',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('why', sa.String(length=120), nullable=True),
    sa.Column('when', sa.String(length=64), nullable=True),
    sa.Column('how', sa.String(length=32), nullable=True),
    sa.Column('experience', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_unique_constraint(None, 'my_information', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_information', type_='unique')
    op.drop_table('more_about_me')
    # ### end Alembic commands ###
