"""empty message

Revision ID: 65c433d5ae17
Revises: 29ff848f57ec
Create Date: 2022-07-31 08:32:57.307905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c433d5ae17'
down_revision = '29ff848f57ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('availabilities_user_avail_owner_fkey', 'availabilities', type_='foreignkey')
    op.create_foreign_key(None, 'availabilities', 'tutoring', ['user_avail_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availabilities', type_='foreignkey')
    op.create_foreign_key('availabilities_user_avail_owner_fkey', 'availabilities', 'user', ['user_avail_owner'], ['id'])
    # ### end Alembic commands ###
