"""empty message

Revision ID: 7788eab991b5
Revises: 046fb8517d8e
Create Date: 2022-07-30 09:12:16.110228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7788eab991b5'
down_revision = '046fb8517d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades_possible',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_possible',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('avail_from', sa.String(length=32), nullable=True))
    op.add_column('students', sa.Column('avail_to', sa.String(length=32), nullable=True))
    op.add_column('subjects', sa.Column('subject_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'students', ['subject_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'subject_owner')
    op.drop_column('students', 'avail_to')
    op.drop_column('students', 'avail_from')
    op.drop_table('subject_possible')
    op.drop_table('grades_possible')
    # ### end Alembic commands ###
