"""empty message

Revision ID: 93deeef4ad3d
Revises: a6b62c1a28cb
Create Date: 2022-07-21 15:05:53.311888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93deeef4ad3d'
down_revision = 'a6b62c1a28cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_information', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'my_information', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_information', type_='foreignkey')
    op.drop_column('my_information', 'user_id')
    # ### end Alembic commands ###
