"""empty message

Revision ID: 975f51cbac11
Revises: 2484fdae8c18
Create Date: 2022-08-04 20:00:04.225456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975f51cbac11'
down_revision = '2484fdae8c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_tutor_course',
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], )
    )
    op.drop_column('course', 'tutor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('tutor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('association_tutor_course')
    # ### end Alembic commands ###
