"""empty message

Revision ID: ba3506592568
Revises: 65c433d5ae17
Create Date: 2022-07-31 16:49:46.844412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3506592568'
down_revision = '65c433d5ae17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalities', sa.Column('user_modality_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modalities', 'tutoring', ['user_modality_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modalities', type_='foreignkey')
    op.drop_column('modalities', 'user_modality_owner')
    # ### end Alembic commands ###
