"""empty message

Revision ID: bef75d9db971
Revises: f1240fded1ff
Create Date: 2022-08-04 17:03:16.950092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef75d9db971'
down_revision = 'f1240fded1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_table', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_table', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_table', type_='foreignkey')
    op.drop_column('course_table', 'course_id')
    # ### end Alembic commands ###
