"""empty message

Revision ID: c568a168211c
Revises: 1ea9f089c20c
Create Date: 2022-10-01 14:57:45.199769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c568a168211c'
down_revision = '1ea9f089c20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_upload_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'upload_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_upload_id_fkey', 'user', 'upload', ['upload_id'], ['id'])
    # ### end Alembic commands ###
