"""empty message

Revision ID: cc4f425fbceb
Revises: 96c427d4aa87
Create Date: 2022-07-22 10:38:52.194170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4f425fbceb'
down_revision = '96c427d4aa87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maths', sa.String(length=32), nullable=True),
    sa.Column('physics', sa.String(length=32), nullable=True),
    sa.Column('svt', sa.String(length=32), nullable=True),
    sa.Column('french', sa.String(length=32), nullable=True),
    sa.Column('english', sa.String(length=32), nullable=True),
    sa.Column('spanish', sa.String(length=32), nullable=True),
    sa.Column('history', sa.String(length=32), nullable=True),
    sa.Column('geopolitics', sa.String(length=32), nullable=True),
    sa.Column('modalities', sa.String(length=32), nullable=True),
    sa.Column('engagement', sa.String(length=32), nullable=True),
    sa.Column('starting_date', sa.String(length=32), nullable=True),
    sa.Column('ending_date', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('monday', sa.String(length=10), nullable=True),
    sa.Column('tuesday', sa.String(length=10), nullable=True),
    sa.Column('wednesday', sa.String(length=10), nullable=True),
    sa.Column('thursday', sa.String(length=10), nullable=True),
    sa.Column('friday', sa.String(length=10), nullable=True),
    sa.Column('sunday', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutoring')
    # ### end Alembic commands ###
