"""empty message

Revision ID: e362cf7826b2
Revises: 8593d6cac36a
Create Date: 2022-08-02 08:35:56.541600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e362cf7826b2'
down_revision = '8593d6cac36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('availabilities_user_avail_owner_fkey', 'availabilities', type_='foreignkey')
    op.create_foreign_key(None, 'availabilities', 'user', ['user_avail_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availabilities', type_='foreignkey')
    op.create_foreign_key('availabilities_user_avail_owner_fkey', 'availabilities', 'tutoring', ['user_avail_owner'], ['id'])
    # ### end Alembic commands ###
