"""empty message

Revision ID: ebfcec75cd00
Revises: cc4f425fbceb
Create Date: 2022-07-22 10:40:25.408841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfcec75cd00'
down_revision = 'cc4f425fbceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutoring', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'tutoring', ['id'])
    op.create_unique_constraint(None, 'tutoring', ['user_id'])
    op.create_foreign_key(None, 'tutoring', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutoring', type_='foreignkey')
    op.drop_constraint(None, 'tutoring', type_='unique')
    op.drop_constraint(None, 'tutoring', type_='unique')
    op.drop_column('tutoring', 'user_id')
    # ### end Alembic commands ###
