"""empty message

Revision ID: f1df99449354
Revises: 5ef4e3d174c8
Create Date: 2022-08-04 17:09:25.764441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1df99449354'
down_revision = '5ef4e3d174c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course_table',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.create_table('tutor_course_table',
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], )
    )
    op.drop_table('course_table')
    op.alter_column('course', 'tutor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'student',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'student',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course', 'tutor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('course_table',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_table_course_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='course_table_student_id_fkey'),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], name='course_table_tutor_id_fkey')
    )
    op.drop_table('tutor_course_table')
    op.drop_table('student_course_table')
    # ### end Alembic commands ###
